### ISSUE TITLE
Plugin does not record most of the time spent compiling a module

### ISSUE THREAD

**Issue by parsonsmatt** [MercuryTechnologies/opentelemetry-plugin#13]
A log was printed out with `-ddump-timings` to identify how long a module took to build:

```
Parser [Database.DocumentationSpec]: alloc=44907560 time=39.947
Simplify [expr]: alloc=18632 time=0.136
CorePrep [expr]: alloc=14136 time=0.061
GHC.StgToByteCode [Ghci1]: alloc=28456 time=0.191
Simplify [expr]: alloc=15704 time=0.085
CorePrep [expr]: alloc=13344 time=0.044
GHC.StgToByteCode [Ghci1]: alloc=24768 time=0.161
Renamer/typechecker [Database.DocumentationSpec]: alloc=439039344 time=216832.474
Desugar [Database.DocumentationSpec]: alloc=48063120 time=405.764

--- we start recording here 
Core plugin:  begin module [Database.DocumentationSpec]: alloc=29696 time=1.101
Core plugin:  begin Core plugin:  Mercury lint [Database.DocumentationSpec]: alloc=38880 time=0.280
Core plugin:  Mercury lint [Database.DocumentationSpec]: alloc=28624 time=0.125
Core plugin:  end Core plugin:  Mercury lint [Database.DocumentationSpec]: alloc=33712 time=0.677
Core plugin:  begin Simplifier [Database.DocumentationSpec]: alloc=31568 time=0.066
Simplifier [Database.DocumentationSpec]: alloc=666750984 time=2530.444
Core plugin:  end Simplifier [Database.DocumentationSpec]: alloc=31888 time=0.267
Core plugin:  end module [Database.DocumentationSpec]: alloc=31600 time=0.190

-- we stop recording here
CoreTidy [Database.DocumentationSpec]: alloc=387395392 time=1724.774
CorePrep [Database.DocumentationSpec]: alloc=130213976 time=1599.078
CoreToStg [Database.DocumentationSpec]: alloc=369391800 time=2548.724
CodeGen [Database.DocumentationSpec]: alloc=7408521440 time=69863.540
WriteIface [/Users/maximiliantagher/Documents/Mercury/hs/mercury-web-backend/dist-newstyle/build/aarch64-osx/ghc-9.6.2/mwb-0/l/test-dev/noopt/build/test-dev/Database/DocumentationSpec.dyn_hi]: alloc=71203944 time=342.080
systool:touch: alloc=76000 time=77.604
CorePrep [Database.DocumentationSpec]: alloc=130214064 time=1524.946
GHC.StgToByteCode [Database.DocumentationSpec]: alloc=791826696 time=2901.525
systool:as: alloc=123616 time=15881.902
```

Those time values are derived from `getCPUTime`, which returns the picoseconds, and processed:

```haskell
                time = realToFrac (end - start) * 1e-9
```

Assuming the times listed are `ms` (1e12 * 1e-9 = 1e-3 ??), then we were spending 316 seconds in this module and only recording 2.5s. That's a pretty huge difference! I believe some of this comes down to the TemplateHaskell invocation (see #11), which isn't currently tracked - I'm guessing that's the lines starting with `Simplifer [expr]` and ending with `GHC.StgToByteCode [Ghci1]`.

[The GHC plugin interface](https://hackage.haskell.org/package/ghc-9.6.1/docs/GHC-Driver-Plugins.html) gives us a few options to record information.

1. `parsedResultAction` is called after parsing completes.
2. `tcPlugin` and `typeCheckResultAction` can run during the typechecking phase
3. `spliceRunAction` runs before a splice or quasiquote is run
4. `interfaceLoadAction` is called by `GHC.IFace.Load` when an interface is successfully loaded.
5. `driverPlugin` updates the `HscEnv`, right after plugin loading - "This can be used to register hooks or tweak any field of DynFlags before doing actual work on a module."

The essential problem with the plugin architecture, for our purposes, is that we don't get a nice pairing of `before/after` hooks, and we don't have a clear place to see when the whole module is really *done*, as far as I can tell.

`driverPlugin` works on the [`HscEnv`](https://hackage.haskell.org/package/ghc-9.6.1/docs/GHC-Driver-Env-Types.html#t:HscEnv), which has a field `hsc_hooks`. [`Hooks`](https://hackage.haskell.org/package/ghc-9.6.1/docs/GHC-Driver-Hooks.html#t:Hooks) is an abstract type. [Looking at the source](https://hackage.haskell.org/package/ghc-9.6.1/docs/src/GHC.Driver.Hooks.html#Hooks), it isn't documented. There's a `runPhaseHook`, which links to [`GHC.Driver.Pipeline.Phases`](https://hackage.haskell.org/package/ghc-9.6.1/docs/src/GHC.Driver.Pipeline.Phases.html#PhaseHook). This actually gives us the ability to put a hook around a ton of stuff - including several phases (like `T_As`?) that can feasibly be used to close a span out for the entire module.

So I think, to properly capture module timing, we need to investigate the full pipeline and understand when/if these hooks are called.

**Comment by parsonsmatt** [comment]
h/t @wavewave for calling out [`nextPhase`](https://github.com/ghc/ghc/blob/ghc-9.6.2-release/compiler/GHC/Driver/Phases.hs#L150) - a "conservative approximation to the next phase." Looks like `Unlit` is the first, then a few others. [`startPhase`](https://github.com/ghc/ghc/blob/ghc-9.6.2-release/compiler/GHC/Driver/Phases.hs#L178) appears to be a function from file suffix to the initial phase - for  most `hs` file, it's `Cpp`, with `Unlit` only for `lhs` files.

So I think that - for each `startPhase` - we can try and initialize a span. And then at `StopLn` we can close the span.

(Maybe we can even catch the 'compiler error' state and report spans for error modules, too?)

**Comment by parsonsmatt** [comment]
There's prior art in the [`ghc-specter`](https://github.com/MercuryTechnologies/ghc-specter/blob/main/plugin/src-ghc96/Plugin/GHCSpecter/Hooks.hs#L361) repo too for this!

**Comment by wavewave** [comment]
Oh, creating a span for each module in driverPlugin will not work. Once driverPlugin is loaded for the first module of the whole compilation, it will not be reloaded. In GHC loadPlugin code, there is a check for whether to reload driver plugin or not. 
So instead, I used this: https://github.com/MercuryTechnologies/ghc-specter/blob/3127a8a7fb61c18d57feef951ce453283ac28aa1/plugin/src-ghc96/Plugin/GHCSpecter/Hooks.hs#L283
for marking the start of the compilation of a module. Most of cases without any preprocessors like hsc2hs,  `T_Hsc` is the start of parsing Haskell code. 
Definitely, this should be improved with more correct treatment by checking all the phase start/end and the corner cases. The approach above is just practically working for most of cases.
