### ISSUE TITLE
baffling error in `installPhase` when using `nix build` with a library

### ISSUE THREAD

**Issue by vaibhavsagar** [MercuryTechnologies/opentelemetry-plugin#15]
I'd love to be able to use this with `nix build --impure`, especially on a project like [IHaskell](https://github.com/IHaskell/IHaskell) which has multiple subprojects. However, when I try on e.g. this [minimal repro](https://github.com/vaibhavsagar/experiments/tree/28f977ded2252334463257121d6bcf978e26fb2a/opentelemetry-plugin-bug) I get the following error:

```
$ nix build
<...>
error: builder for '/nix/store/rlc7i7m24g6vmn33rsfgjf5g8nx1rngz-opentelemetry-plugin-bug-0.1.0.0.drv' failed with exit code 1;
       last 10 log lines:
       > Running phase: installPhase
       > Installing library in /nix/store/kf50fs84bhq8kz1j9s7yxpmjx300bk95-opentelemetry-plugin-bug-0.1.0.0/lib/ghc-9.6.3/lib/x86_64-linux-ghc-9.6.3/opentelemetry-plugin-bug-0.1.0.0-7asVorM6HCnGgZdLWaV8BQ
       > Error: Setup: '/nix/store/x7kmxv5bql8xjwhkk1m3y4g02z9m23sa-ghc-9.6.3/bin/ghc'
       > exited with an error:
       > <command line>: Could not load module ‘OpenTelemetry.Plugin’
       > It is a member of the hidden package ‘opentelemetry-plugin-1.2.0’.
       > Perhaps you need to add ‘opentelemetry-plugin’ to the build-depends in your
       > .cabal file.
       > Use -v (or `:set -v` in ghci) to see a list of the files searched for.
       >
       For full logs, run 'nix log /nix/store/rlc7i7m24g6vmn33rsfgjf5g8nx1rngz-opentelemetry-plugin-bug-0.1.0.0.drv'.
```

which is extremely surprising to me because I have no idea how to resolve this. FWIW I didn't have this issue when building an executable instead of a library.

If you would like a larger example, [here's a commit of IHaskell that demonstrates the same issue](https://github.com/IHaskell/IHaskell/commit/5577eb28c4b8ddd759da5b37254cd1f354a61fac).

**Comment by Gabriella439** [comment]
I don't know if this is related to the error you're seeing, but the first thing I noticed is that you also need `ghc-options: -plugin-package opentelemetry-plugin`

**Comment by Gabriella439** [comment]
Yeah, I'd accept such a PR!
